[package]
name = "yjs_tree"
version = "0.1.0"
description = "A Rust library implementing a CRDT-based tree data structure powered by Yjs"
authors = ["Michelle Tilley <michelle@tilley.tech>"]
repository = "https://github.com/binarymuse/yjs_tree"
edition = "2021"
license = "MIT"

[dependencies]
yrs = "0.22.0"
